### ISSUE TITLE
Support plugins/tools that aren't hosted on GitHub

### ISSUE THREAD

**Issue by simonw** [simonw/datasette.io#101]
> Maybe I should have a `directory.yml` file to replace `tool_repos.yml` and `plugin_repos.yml` which combines the data from both and provides me with a hook to add custom extras, like a list of tags or a URL to an image (if the repo doesn't provide one).

_Originally posted by @simonw in https://github.com/simonw/datasette.io/issues/98#issuecomment-1093127983_

Possible design for that format:
```yaml
- package: datasette-graphql
  github: simonw/datasette-graphql
  plugin: true
  tags:
  - graphql
  - api
  hooks:
  - database_actions
  - extra_template_vars
  - menu_links
  - register_routes
  - startup
  - table_actions
```
