### ISSUE TITLE
Parts of YAML file do not work when db name is "off"

### ISSUE THREAD

**Issue by CharlesNepote** [simonw/datasette.io#117]
I guess this issue is not very important and probably rare.

To reproduce:
* create and populate a db named `off.db`
* in the yaml file, add any kind of information below `databases:\n   off:`
* the data are not taken into account (because "off" is interpreted as "false")

YAML file:
```yaml
title: Some title
description_html: |-
  <p>This is an experiment.</p>
databases:
  off:
    tables:
      products_from_owners:
        title: products_from_owners*
        description_html: |-
          <p>Description</p>
```

The result for http://xxxx.xxx/-/metadata gives:
```json
{
    "title": "Some title",
    "description_html": "<p>This is an experiment.</p>",
    "databases": {
        "false": {
            "tables": {
                "products_from_owners": {
                    "title": "products_from_owners*",
                    "description_html": "<p>Description</p>"
                }
            }
        }
    }
}
```
=> see the `"false"` instead of `"off"`.

**Comment by simonw** [comment]
Oh that's a classic YAML problem, I hadn't realized it would affect Datasette like this!

You should be able to fix it by quoting the `off` key like this:

```yaml
title: Some title
description_html: |-
  <p>This is an experiment.</p>
databases:
  "off":
    tables:
      products_from_owners:
        title: products_from_owners*
        description_html: |-
          <p>Description</p>
```
