### ISSUE TITLE
Use shot-scraper to create tutorial screenshots

### ISSUE THREAD

**Issue by simonw** [simonw/datasette.io#95]
For https://datasette.io/tutorials/explore

**Comment by simonw** [comment]
Work in progress:
```yaml
- url: https://congress-legislators.datasettes.com/legislators
  width: 1000
  height: 910
  quality: 85
  output: legislators-index.jpg
- url: https://congress-legislators.datasettes.com/legislators/legislator_terms
  javascript: |
    document.querySelector("table").scrollIntoView();
  height: 400
  width: 850
  output: foreign-key-links.jpg
- url: https://congress-legislators.datasettes.com/legislators/legislators/K000393
  width: 1000
  height: 450
  javascript:
    document.querySelector("footer").style.display = "none"
  output: row-with-links.jpg
```
